# Generated by Django 2.2.5 on 2021-04-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210407_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='set_name',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
