# Generated by Django 2.2.5 on 2021-04-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
