# Generated by Django 2.2.5 on 2021-04-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='txt',
            field=models.CharField(max_length=350),
        ),
    ]
